FROM mesosphere/mesos:0.27.1-2.0.226.ubuntu1404

ENV MESOS_WORK_DIR /tmp/mesos
ENV MESOS_LOG_DIR /var/log/mesos
ENV MESOS_NATIVE_JAVA_LIBRARY /usr/local/lib/libmesos.so

VOLUME /tmp/mesos

VOLUME /var/log/mesos